URL_SERVICE = "https://d2ad8589-ad2d-4828-9fb7-4e636651dd4a.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"